"""HR Core: departments + employee directory (ARCH §3). Both RLS-scoped.

departments.manager_id and employees.department_id/reporting_manager_id form a
small cycle (a department's manager is an employee; an employee belongs to a
department) — handled in the migration by adding departments.manager_id via
ALTER TABLE after employees exists. The ORM models below declare it directly;
SQLAlchemy only needs this for query building, not table creation (migrations
are hand-written, not autogenerated).
"""
import uuid
from datetime import date

from sqlalchemy import Date, ForeignKey, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.core.models import TenantBase


class Department(TenantBase):
    __tablename__ = "departments"
    name: Mapped[str] = mapped_column(String(200))
    parent_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("departments.id"), nullable=True
    )
    manager_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("employees.id"), nullable=True
    )


class Employee(TenantBase):
    __tablename__ = "employees"
    user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id"), nullable=True
    )  # null until the person is onboarded with a login
    department_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("departments.id"), nullable=True
    )
    reporting_manager_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("employees.id"), nullable=True
    )
    full_name: Mapped[str] = mapped_column(String(200))
    email: Mapped[str | None] = mapped_column(String(200), nullable=True)
    status: Mapped[str] = mapped_column(String(20), default="active")  # active|probation|exited
    joined_on: Mapped[date | None] = mapped_column(Date, nullable=True)
